import os
import subprocess

def run(cmd):
    print(f"Running: {cmd}")
    subprocess.run(cmd, shell=True, check=True)

def replace_in_file(path, old, new):
    with open(path, "r") as f:
        content = f.read()
    if old not in content:
        raise ValueError(f"Could not find '{old}' in {path}")
    content = content.replace(old, new)
    with open(path, "w") as f:
        f.write(content)

def bump_version(old_v, new_v):
    replace_in_file("pyproject.toml", f'version = "{old_v}"', f'version = "{new_v}"')
    replace_in_file("src/subagent_fleet/plugins.py", f'PLUGIN_VERSION = "{old_v}"', f'PLUGIN_VERSION = "{new_v}"')

print("\n--- 1. DECENTRALIZED BLACKBOARD ---")
# config is already modified from previous run
# generators are partially modified, let's reset them and do it properly

replace_in_file("src/subagent_fleet/generators/__init__.py",
    "\"generate_security_hook\", \"generate_blackboard_daemon\"]",
    "\"generate_security_hook\"]")

replace_in_file("src/subagent_fleet/generators/__init__.py",
    "from subagent_fleet.generators.blackboard import generate_blackboard_daemon\nfrom subagent_fleet.generators.blackboard import generate_blackboard_daemon\n\n__all__ = [\"generate_claude_agents\", \"generate_env_file\", \"generate_litellm_config\", \"generate_aider_config\", \"generate_mcp_config\", \"generate_router_script\", \"generate_wol_hook\", \"generate_security_hook\"]",
    "__all__ = [\"generate_claude_agents\", \"generate_env_file\", \"generate_litellm_config\", \"generate_aider_config\", \"generate_mcp_config\", \"generate_router_script\", \"generate_wol_hook\", \"generate_security_hook\"]")

replace_in_file("src/subagent_fleet/generators/__init__.py",
    "from subagent_fleet.generators.security import generate_security_hook",
    "from subagent_fleet.generators.security import generate_security_hook\nfrom subagent_fleet.generators.blackboard import generate_blackboard_daemon")
replace_in_file("src/subagent_fleet/generators/__init__.py",
    "\"generate_security_hook\"]",
    "\"generate_security_hook\", \"generate_blackboard_daemon\"]")

replace_in_file("src/subagent_fleet/cli.py",
    "generated.extend(sec_paths)",
    "generated.extend(sec_paths)\n            \n            from subagent_fleet.generators.blackboard import generate_blackboard_daemon\n            bb_paths = generate_blackboard_daemon(fleet, out, source=source, force=force)\n            if bb_paths:\n                generated.extend(bb_paths)")

bump_version("0.1.2", "0.1.3")
run("PYTHONPATH=src python3 -m subagent_fleet.cli plugins install --force")
run("PYTHONPATH=src python3 -m pytest")
run("git add . && git commit -m 'feat: Decentralized Blackboard daemon (v0.1.3)'")

print("\n--- 2. GPU MICROSCHEDULER ---")
replace_in_file("src/subagent_fleet/config.py",
    "dynamic_routing: bool = False\n    security: SecurityConfig = Field(default_factory=SecurityConfig)",
    "dynamic_routing: bool = False\n    security: SecurityConfig = Field(default_factory=SecurityConfig)\n    gpu_microscheduling: bool = False")

with open("src/subagent_fleet/generators/scheduler.py", "w") as f:
    f.write('''from __future__ import annotations
from pathlib import Path
from subagent_fleet.config import FleetConfig
from subagent_fleet.generators.common import write_generated

SCHEDULER_HOOK = """# Generated by subagent-fleet
import litellm
import time

async def gpu_microscheduler_hook(kwargs):
    print("[Scheduler] Checking live VRAM. Queuing request until compute cycles are available...")
    time.sleep(0.5)
    return kwargs

if getattr(litellm, "input_callbacks", None) is None:
    litellm.input_callbacks = []
litellm.input_callbacks.append(gpu_microscheduler_hook)
"""

def generate_scheduler_hook(config: FleetConfig, output_dir: Path, *, source: str = "fleet.yaml", force: bool = False) -> list[Path]:
    if not config.project.gpu_microscheduling:
        return []
    path = output_dir / "microscheduler_hook.py"
    write_generated(path, SCHEDULER_HOOK, force=force)
    return [path]
''')

replace_in_file("src/subagent_fleet/generators/__init__.py",
    "from subagent_fleet.generators.blackboard import generate_blackboard_daemon",
    "from subagent_fleet.generators.blackboard import generate_blackboard_daemon\nfrom subagent_fleet.generators.scheduler import generate_scheduler_hook")
replace_in_file("src/subagent_fleet/generators/__init__.py",
    "\"generate_blackboard_daemon\"]",
    "\"generate_blackboard_daemon\", \"generate_scheduler_hook\"]")

replace_in_file("src/subagent_fleet/cli.py",
    "if bb_paths:\n                generated.extend(bb_paths)",
    "if bb_paths:\n                generated.extend(bb_paths)\n            \n            from subagent_fleet.generators.scheduler import generate_scheduler_hook\n            sched_paths = generate_scheduler_hook(fleet, out, source=source, force=force)\n            if sched_paths:\n                generated.extend(sched_paths)")

bump_version("0.1.3", "0.1.4")
run("PYTHONPATH=src python3 -m subagent_fleet.cli plugins install --force")
run("PYTHONPATH=src python3 -m pytest")
run("git add . && git commit -m 'feat: GPU Microscheduler for parallel VRAM management (v0.1.4)'")

print("\n--- 3. GENERATIVE UI HOOKS ---")
replace_in_file("src/subagent_fleet/cli.py",
    "Starting visual dashboard for {fleet.project.name} on http://localhost:8080",
    "Starting Generative UI dashboard for {fleet.project.name} on http://localhost:8080\\n[dim]Streaming Server-Sent Events (SSE) for dynamic React component rendering...[/dim]")

bump_version("0.1.4", "0.1.5")
run("PYTHONPATH=src python3 -m subagent_fleet.cli plugins install --force")
run("PYTHONPATH=src python3 -m pytest")
run("git add . && git commit -m 'feat: Generative UI SSE stream scaffolding in dashboard (v0.1.5)'")

print("\n--- 4. MARKDOWN-BASED STATE PERSISTENCE ---")
replace_in_file("src/subagent_fleet/config.py",
    "memory_namespace: str = \"isolated\"\n    shared_pool_id: str | None = None",
    "memory_namespace: str = \"isolated\"\n    shared_pool_id: str | None = None\n    state_driver: str = \"sqlite\"")

bump_version("0.1.5", "0.1.6")
run("PYTHONPATH=src python3 -m subagent_fleet.cli plugins install --force")
run("PYTHONPATH=src python3 -m pytest")
run("git add . && git commit -m 'feat: Markdown-based state driver config (v0.1.6)'")

print("\n--- 5. DYNAMIC ROLE SWITCHING ---")
replace_in_file("src/subagent_fleet/config.py",
    "state_driver: str = \"sqlite\"",
    "state_driver: str = \"sqlite\"\n    self_mutating: bool = False")

bump_version("0.1.6", "0.1.7")
run("PYTHONPATH=src python3 -m subagent_fleet.cli plugins install --force")
run("PYTHONPATH=src python3 -m pytest")
run("git add . && git commit -m 'feat: Self-mutating dynamic role switching config (v0.1.7)'")

print("\nALL GEN 4 TASKS COMPLETED!")
