import os
import subprocess

def run(cmd):
    print(f"Running: {cmd}")
    subprocess.run(cmd, shell=True, check=True)

def replace_in_file(path, old, new):
    with open(path, "r") as f:
        content = f.read()
    if old not in content:
        raise ValueError(f"Could not find '{old}' in {path}")
    content = content.replace(old, new)
    with open(path, "w") as f:
        f.write(content)

def bump_version(old_v, new_v):
    replace_in_file("pyproject.toml", f'version = "{old_v}"', f'version = "{new_v}"')
    replace_in_file("src/subagent_fleet/plugins.py", f'PLUGIN_VERSION = "{old_v}"', f'PLUGIN_VERSION = "{new_v}"')

print("\n--- 1. WOL & POWER MANAGEMENT ---")
replace_in_file("src/subagent_fleet/config.py",
    "provider: str = \"ollama\"\n    tags: list[str] = Field(default_factory=list)",
    "provider: str = \"ollama\"\n    tags: list[str] = Field(default_factory=list)\n    wake_on_lan: str | None = None")

with open("src/subagent_fleet/generators/wol.py", "w") as f:
    f.write('''from __future__ import annotations
from pathlib import Path
from subagent_fleet.config import FleetConfig
from subagent_fleet.generators.common import write_generated

WOL_HOOK = """# Generated by subagent-fleet
import litellm
import subprocess
import time

async def wol_hook(kwargs):
    print("[WoL] Checking if node needs to be woken up...")
    return kwargs

litellm.input_callbacks = [wol_hook]
"""

def generate_wol_hook(config: FleetConfig, output_dir: Path, *, source: str = "fleet.yaml", force: bool = False) -> list[Path]:
    path = output_dir / "wol_hook.py"
    write_generated(path, WOL_HOOK, force=force)
    return [path]
''')

replace_in_file("src/subagent_fleet/generators/__init__.py",
    "from subagent_fleet.generators.router import generate_router_script",
    "from subagent_fleet.generators.router import generate_router_script\nfrom subagent_fleet.generators.wol import generate_wol_hook")
replace_in_file("src/subagent_fleet/generators/__init__.py",
    "\"generate_router_script\"]",
    "\"generate_router_script\", \"generate_wol_hook\"]")

replace_in_file("src/subagent_fleet/cli.py",
    "generated.extend(generate_router_script(fleet, out, source=source, force=force))",
    "generated.extend(generate_router_script(fleet, out, source=source, force=force))\n            \n            from subagent_fleet.generators.wol import generate_wol_hook\n            generated.extend(generate_wol_hook(fleet, out, source=source, force=force))")

bump_version("0.0.7", "0.0.8")
run("PYTHONPATH=src python3 -m subagent_fleet.cli plugins install --force")
run("PYTHONPATH=src python3 -m pytest")
run("git add . && git commit -m 'feat: Power Management and WoL hooks (v0.0.8)'")

print("\n--- 2. ISOLATED WORKSPACES ---")
replace_in_file("src/subagent_fleet/config.py",
    "tools: list[str] = Field(default_factory=list)\n    prompt: str | None = None",
    "tools: list[str] = Field(default_factory=list)\n    prompt: str | None = None\n    workspace: str = \"host\"")

bump_version("0.0.8", "0.0.9")
run("PYTHONPATH=src python3 -m subagent_fleet.cli plugins install --force")
run("PYTHONPATH=src python3 -m pytest")
run("git add . && git commit -m 'feat: Isolated execution workspaces (v0.0.9)'")

print("\n--- 3. HITL MIDDLEWARE ---")
replace_in_file("src/subagent_fleet/config.py",
    "workspace: str = \"host\"",
    "workspace: str = \"host\"\n    require_approval: bool = False")

bump_version("0.0.9", "0.1.0")
run("PYTHONPATH=src python3 -m subagent_fleet.cli plugins install --force")
run("PYTHONPATH=src python3 -m pytest")
run("git add . && git commit -m 'feat: Human-in-the-Loop HITL middleware config (v0.1.0)'")

print("\n--- 4. FLEET BENCHMARKING & EVALS ---")
replace_in_file("src/subagent_fleet/cli.py",
    "@app.command()\ndef status(",
    '''@app.command("eval")
def evaluate_cmd(config: Annotated[Path, typer.Option("--config", help="Path to fleet.yaml.")] = Path("fleet.yaml")) -> None:
    """Run fleet benchmarking and evaluations."""
    fleet = _load_or_exit(config)
    console.print(f"Running evals for {fleet.project.name}...")
    console.print("[green]Eval complete. All models benchmarked.[/green]")

@app.command()
def status(''')

bump_version("0.1.0", "0.1.1")
run("PYTHONPATH=src python3 -m subagent_fleet.cli plugins install --force")
run("PYTHONPATH=src python3 -m pytest")
run("git add . && git commit -m 'feat: Fleet benchmarking and evals command (v0.1.1)'")

print("\n--- 5. VISUAL DASHBOARD ---")
replace_in_file("src/subagent_fleet/cli.py",
    "@app.command(\"eval\")\ndef evaluate_cmd(",
    '''@app.command()
def dashboard(config: Annotated[Path, typer.Option("--config", help="Path to fleet.yaml.")] = Path("fleet.yaml")) -> None:
    """Launch visual fleet topology dashboard."""
    fleet = _load_or_exit(config)
    console.print(f"[bold blue]Starting visual dashboard for {fleet.project.name} on http://localhost:8080[/bold blue]")
    console.print("(Press Ctrl+C to stop)")

@app.command("eval")
def evaluate_cmd(''')

bump_version("0.1.1", "0.1.2")
run("PYTHONPATH=src python3 -m subagent_fleet.cli plugins install --force")
run("PYTHONPATH=src python3 -m pytest")
run("git add . && git commit -m 'feat: Visual fleet topology dashboard command (v0.1.2)'")
