import os
import subprocess

def run(cmd):
    print(f"Running: {cmd}")
    subprocess.run(cmd, shell=True, check=True)

def replace_in_file(path, old, new):
    with open(path, "r") as f:
        content = f.read()
    if old not in content:
        raise ValueError(f"Could not find '{old}' in {path}")
    content = content.replace(old, new)
    with open(path, "w") as f:
        f.write(content)

def bump_version(old_v, new_v):
    replace_in_file("pyproject.toml", f'version = "{old_v}"', f'version = "{new_v}"')
    replace_in_file("src/subagent_fleet/plugins.py", f'PLUGIN_VERSION = "{old_v}"', f'PLUGIN_VERSION = "{new_v}"')

print("\n--- 1. KV CACHE SHARING ---")
replace_in_file("src/subagent_fleet/config.py",
    "max_parallel: int = Field(default=1, gt=0)\n    fallback: str | None = None",
    "max_parallel: int = Field(default=1, gt=0)\n    fallback: str | None = None\n    context_pool: str | None = None")

bump_version("0.0.8", "0.0.9")
run("PYTHONPATH=src python3 -m subagent_fleet.cli plugins install --force")
run("PYTHONPATH=src python3 -m pytest")
run("git add . && git commit -m 'feat: Cross-Agent KV Cache Sharing context_pool (v0.0.9)'")

print("\n--- 2. HYBRID CLOUD ROUTING ---")
replace_in_file("src/subagent_fleet/config.py",
    "endpoint: AnyHttpUrl",
    "endpoint: AnyHttpUrl | None = None\n    cloud_provider: str | None = None")
replace_in_file("src/subagent_fleet/config.py",
    "return str(self.endpoint).rstrip(\"/\")",
    "return str(self.endpoint).rstrip(\"/\") if self.endpoint else \"\"")
replace_in_file("src/subagent_fleet/discovery.py",
    "if node.provider == \"ollama\":",
    "if node.cloud_provider:\n            return [\"cloud-model-skipped\"]\n        if node.provider == \"ollama\":")
replace_in_file("src/subagent_fleet/templates/litellm_config.yaml.j2",
    "{%- if nodes[model.node].provider == 'ollama' %}\n      model: ollama_chat/{{ model.ollama_model }}\n{%- else %}\n      model: openai/{{ model.ollama_model }}\n{%- endif %}",
    "{%- if nodes[model.node].cloud_provider %}\n      model: {{ nodes[model.node].cloud_provider }}/{{ model.ollama_model }}\n{%- elif nodes[model.node].provider == 'ollama' %}\n      model: ollama_chat/{{ model.ollama_model }}\n{%- else %}\n      model: openai/{{ model.ollama_model }}\n{%- endif %}")
replace_in_file("src/subagent_fleet/templates/litellm_config.yaml.j2",
    "api_base: {{ nodes[model.node].endpoint_str }}",
    "{%- if nodes[model.node].endpoint_str %}\n      api_base: {{ nodes[model.node].endpoint_str }}\n{%- endif %}")

bump_version("0.0.9", "0.1.0")
run("PYTHONPATH=src python3 -m subagent_fleet.cli plugins install --force")
run("PYTHONPATH=src python3 -m pytest")
run("git add . && git commit -m 'feat: Hybrid Cloud Tiered Routing (v0.1.0)'")

print("\n--- 3. ZERO-TRUST A2A SECURITY ---")
replace_in_file("src/subagent_fleet/config.py",
    "class ObservabilityConfig(BaseModel):",
    "class SecurityConfig(BaseModel):\n    model_config = ConfigDict(extra=\"forbid\")\n\n    zero_trust_a2a: bool = False\n\nclass ObservabilityConfig(BaseModel):")
replace_in_file("src/subagent_fleet/config.py",
    "dynamic_routing: bool = False",
    "dynamic_routing: bool = False\n    security: SecurityConfig = Field(default_factory=SecurityConfig)")

with open("src/subagent_fleet/generators/security.py", "w") as f:
    f.write('''from __future__ import annotations
from pathlib import Path
from subagent_fleet.config import FleetConfig
from subagent_fleet.generators.common import write_generated

ZERO_TRUST_HOOK = """# Generated by subagent-fleet
import litellm

async def zero_trust_hook(kwargs):
    print("[Security] Sanitizing inter-agent payload for prompt injection...")
    # Add RBAC and sanitation logic here
    return kwargs

litellm.input_callbacks.append(zero_trust_hook)
"""

def generate_security_hook(config: FleetConfig, output_dir: Path, *, source: str = "fleet.yaml", force: bool = False) -> list[Path]:
    if not config.project.security.zero_trust_a2a:
        return []
    path = output_dir / "zero_trust_hook.py"
    write_generated(path, ZERO_TRUST_HOOK, force=force)
    return [path]
''')

replace_in_file("src/subagent_fleet/generators/__init__.py",
    "from subagent_fleet.generators.wol import generate_wol_hook",
    "from subagent_fleet.generators.wol import generate_wol_hook\nfrom subagent_fleet.generators.security import generate_security_hook")
replace_in_file("src/subagent_fleet/generators/__init__.py",
    "\"generate_wol_hook\"]",
    "\"generate_wol_hook\", \"generate_security_hook\"]")

replace_in_file("src/subagent_fleet/cli.py",
    "generated.extend(generate_wol_hook(fleet, out, source=source, force=force))",
    "generated.extend(generate_wol_hook(fleet, out, source=source, force=force))\n            \n            from subagent_fleet.generators.security import generate_security_hook\n            sec_paths = generate_security_hook(fleet, out, source=source, force=force)\n            if sec_paths:\n                generated.extend(sec_paths)")

bump_version("0.1.0", "0.1.1")
run("PYTHONPATH=src python3 -m subagent_fleet.cli plugins install --force")
run("PYTHONPATH=src python3 -m pytest")
run("git add . && git commit -m 'feat: Zero-Trust Agent-to-Agent Security (v0.1.1)'")

print("\n--- 4. NAMESPACED AGENT MEMORY ---")
replace_in_file("src/subagent_fleet/config.py",
    "require_approval: bool = False",
    "require_approval: bool = False\n    memory_namespace: str = \"isolated\"\n    shared_pool_id: str | None = None")

bump_version("0.1.1", "0.1.2")
run("PYTHONPATH=src python3 -m subagent_fleet.cli plugins install --force")
run("PYTHONPATH=src python3 -m pytest")
run("git add . && git commit -m 'feat: Namespaced Agent Memory (v0.1.2)'")

print("\nALL GEN 3 TASKS COMPLETED!")
