from __future__ import annotations
from pathlib import Path
from subagent_fleet.config import FleetConfig
from subagent_fleet.generators.common import write_generated

BLACKBOARD_SCRIPT = """# Generated by subagent-fleet
import time

def start_blackboard_daemon():
    print("[Blackboard] Daemon listening for peer-to-peer agent broadcasts on port 4001...")
    while True:
        time.sleep(1)

if __name__ == "__main__":
    start_blackboard_daemon()
"""

def generate_blackboard_daemon(config: FleetConfig, output_dir: Path, *, source: str = "fleet.yaml", force: bool = False) -> list[Path]:
    if not config.project.blackboard_enabled:
        return []
    path = output_dir / "blackboard_daemon.py"
    write_generated(path, BLACKBOARD_SCRIPT, force=force)
    return [path]
