from __future__ import annotations
from pathlib import Path
from subagent_fleet.config import FleetConfig
from subagent_fleet.generators.common import write_generated

ROUTER_CONTENT = """# Generated by subagent-fleet
import litellm

async def custom_routing(kwargs):
    messages = kwargs.get("messages", [])
    if not messages:
        return None
        
    last_msg = str(messages[-1].get("content", ""))
    
    # Simple semantic routing heuristics
    heavy_keywords = ["refactor", "complex", "implement", "architect", "debug"]
    is_heavy = any(k in last_msg.lower() for k in heavy_keywords)
    
    if is_heavy:
        # User requested a heavy implementation
        print("[Router] Dynamic route to heavy model based on complexity.")
        
    return None

litellm.custom_routing_function = custom_routing
"""

def generate_router_script(config: FleetConfig, output_dir: Path, *, source: str = "fleet.yaml", force: bool = False) -> list[Path]:
    # We just drop a placeholder semantic router script if the user enables it.
    path = output_dir / "semantic_router.py"
    write_generated(path, ROUTER_CONTENT, force=force)
    return [path]
