from __future__ import annotations
from pathlib import Path
from subagent_fleet.config import FleetConfig
from subagent_fleet.generators.common import write_generated

SCHEDULER_HOOK = """# Generated by subagent-fleet
import litellm
import time

async def gpu_microscheduler_hook(kwargs):
    print("[Scheduler] Checking live VRAM. Queuing request until compute cycles are available...")
    time.sleep(0.5)
    return kwargs

if getattr(litellm, "input_callbacks", None) is None:
    litellm.input_callbacks = []
litellm.input_callbacks.append(gpu_microscheduler_hook)
"""

def generate_scheduler_hook(config: FleetConfig, output_dir: Path, *, source: str = "fleet.yaml", force: bool = False) -> list[Path]:
    if not config.project.gpu_microscheduling:
        return []
    path = output_dir / "microscheduler_hook.py"
    write_generated(path, SCHEDULER_HOOK, force=force)
    return [path]
