from __future__ import annotations
from pathlib import Path
from subagent_fleet.config import FleetConfig
from subagent_fleet.generators.common import write_generated

ZERO_TRUST_HOOK = """# Generated by subagent-fleet
import litellm

async def zero_trust_hook(kwargs):
    print("[Security] Sanitizing inter-agent payload for prompt injection...")
    # Add RBAC and sanitation logic here
    return kwargs

if getattr(litellm, "input_callbacks", None) is None:
    litellm.input_callbacks = []
litellm.input_callbacks.append(zero_trust_hook)
"""

def generate_security_hook(config: FleetConfig, output_dir: Path, *, source: str = "fleet.yaml", force: bool = False) -> list[Path]:
    if not config.project.security.zero_trust_a2a:
        return []
    path = output_dir / "zero_trust_hook.py"
    write_generated(path, ZERO_TRUST_HOOK, force=force)
    return [path]
