from __future__ import annotations
from pathlib import Path
from subagent_fleet.config import FleetConfig
from subagent_fleet.generators.common import write_generated

WOL_HOOK = """# Generated by subagent-fleet
import litellm
import subprocess
import time

async def wol_hook(kwargs):
    print("[WoL] Checking if node needs to be woken up...")
    return kwargs

litellm.input_callbacks = [wol_hook]
"""

def generate_wol_hook(config: FleetConfig, output_dir: Path, *, source: str = "fleet.yaml", force: bool = False) -> list[Path]:
    path = output_dir / "wol_hook.py"
    write_generated(path, WOL_HOOK, force=force)
    return [path]
